app:
    mode: dev
    http_port: 8081

database:
    host: localhost
    username: odyssey
    password: odyssey
    dbname: odyssey
    sslmode: disable
    maxIdleConns: 5 
    maxOpenConns: 10
    
log:
    filename: /logs/odyssey.log
    enable_func_call_depth: true

auth:
    secret_key: GO5U9fS8D7WkDay8
    expires: 86400


feedback:
    auth_key: mSedxOqPLTzqQoD704XIDpAHJ6jbJmrBVC8CtthVX5pXgKNAM8jO6vbzlzMnk6tJ
